webhookVersion: 104.0.0+up0.5.0-rc14
provisioningCAPIVersion: 104.0.0+up0.3.0-rc.1
cspAdapterMinVersion: 104.0.0+up4.0.0-rc9
defaultShellVersion: rancher/shell:v0.2.1-rc.7
fleetVersion: 104.0.0+up0.10.0-rc.20
